import Head from 'next/head'
import { Inter } from '@next/font/google'

import Header from '../authBeforeComponents/Header'
import Banner from '../authBeforeComponents/Banner'
import Section from '../authBeforeComponents/Section'
import ScrollContextProvider from '../state/ScrollContextProvider'
import { Fragment } from 'react'
import Popup from '../authBeforeComponents/Popup'

import { useState } from 'react'
import UserContextProvider from '../state/UserContextProvider'

import { useAuthState } from 'react-firebase-hooks/auth';
import { auth } from '../firebase.config'
import AfterHead from '../authAfterComponents/AfterHead'
import AfterSection from '../authAfterComponents/AfterSection'
import AfterRight from '../authAfterComponents/AfterRight'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const [showPopup, setshowPopup] = useState(false);

  const [user, loading, error] = useAuthState(auth as any);

  const styles = {
    AfterBody: 'flex relative'
  }

  if (loading) {
    return (
      <div>
        <p>Initialising User...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div>
        <p>Error: {error.message}</p>
      </div>
    );
  }

  if (user) {
    return (
      <>
        <UserContextProvider>
          <ScrollContextProvider>
            <Fragment>
              <main className='overflow-x-hidden'>
                <AfterHead />
                <div className={styles.AfterBody}>
                  <AfterSection />
                  <AfterRight />
                </div>
              </main>
            </Fragment>
          </ScrollContextProvider>
        </UserContextProvider>
      </>
    );
  }


  return (
    <>
      <Head>
        <title>Medium clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/smallLogo.ico" />
      </Head>
      <ScrollContextProvider>
        <Fragment>
          <main>
            <Header onOpen={() => setshowPopup(true)} />
            <Banner />
            <Section />
          </main>
          <Popup onClose={() => setshowPopup(false)} isVisible={showPopup} />
        </Fragment>
      </ScrollContextProvider>
    </>
  )
}
